var hero_attributes = {
  "abaddon": {
    "midlane": 0,
    "safelane": 5.81,
    "offlane": 6.53,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 6.3,
    "dps": 6.28,
    "push": 4.84,
    "nuke": 2,
    "durable": 9,
    "initial": 2,
    "disable": 4,
    "healing": 8
  },
  "alchemist": {
    "midlane": 7.75,
    "safelane": 5.58,
    "offlane": 5.03,
    "jungle": 4.69,
    "perfer": "Mid Lane",
    "lane": 6.5,
    "dps": 7.82,
    "push": 6.41,
    "nuke": 6,
    "durable": 9,
    "initial": 4,
    "disable": 6,
    "healing": 2
  },
  "ancient-apparition": {
    "midlane": 3.72,
    "safelane": 3.94,
    "offlane": 3.94,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 4,
    "dps": 5.55,
    "push": 2.04,
    "nuke": 4,
    "durable": 1.5,
    "initial": 2,
    "disable": 3,
    "healing": 2.5
  },
  "anti-mage": {
    "midlane": 0,
    "safelane": 5.28,
    "offlane": 4.23,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 5,
    "dps": 6.2,
    "push": 6.55,
    "nuke": 9,
    "durable": 9,
    "initial": 8,
    "disable": 3,
    "healing": 0
  },
  "arc-warden": {
    "midlane": 9.08,
    "safelane": 6.42,
    "offlane": 6.39,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 6,
    "dps": 7.62,
    "push": 5.51,
    "nuke": 8,
    "durable": 6,
    "initial": 3,
    "disable": 4,
    "healing": 3.5
  },
  "axe": {
    "midlane": 0,
    "safelane": 6.7,
    "offlane": 7.78,
    "jungle": 7.78,
    "perfer": "Off Lane",
    "lane": 8.2,
    "dps": 7.72,
    "push": 3.35,
    "nuke": 5.5,
    "durable": 7.5,
    "initial": 8.5,
    "disable": 8,
    "healing": 0
  },
  "bane": {
    "midlane": 8.55,
    "safelane": 8.03,
    "offlane": 8,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 7.5,
    "dps": 4.17,
    "push": 2.43,
    "nuke": 3,
    "durable": 3,
    "initial": 7,
    "disable": 6,
    "healing": 2.5
  },
  "batrider": {
    "midlane": 8.72,
    "safelane": 7.62,
    "offlane": 8.76,
    "jungle": 8.76,
    "perfer": "Off Lane",
    "lane": 8,
    "dps": 5.74,
    "push": 1.99,
    "nuke": 4.5,
    "durable": 6.5,
    "initial": 9.5,
    "disable": 9,
    "healing": 0
  },
  "beastmaster": {
    "midlane": 7.32,
    "safelane": 6.14,
    "offlane": 7.1,
    "jungle": 7.38,
    "perfer": "Off Lane",
    "lane": 6.5,
    "dps": 4.72,
    "push": 5.34,
    "nuke": 5.5,
    "durable": 6,
    "initial": 9,
    "disable": 8,
    "healing": 0
  },
  "bloodseeker": {
    "midlane": 4.96,
    "safelane": 4.42,
    "offlane": 4.53,
    "jungle": 4.48,
    "perfer": "Jungle",
    "lane": 4.5,
    "dps": 7.41,
    "push": 5.17,
    "nuke": 6,
    "durable": 7,
    "initial": 7.5,
    "disable": 3,
    "healing": 3.5
  },
  "bounty-hunter": {
    "midlane": 7.41,
    "safelane": 5.63,
    "offlane": 6.36,
    "jungle": 8.14,
    "perfer": "Off Lane",
    "lane": 5.5,
    "dps": 4.64,
    "push": 2.8,
    "nuke": 7,
    "durable": 4,
    "initial": 3,
    "disable": 7.5,
    "healing": 3.5
  },
  "brewmaster": {
    "midlane": 7.63,
    "safelane": 6.32,
    "offlane": 7.53,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 7,
    "dps": 5.64,
    "push": 4.26,
    "nuke": 4,
    "durable": 9,
    "initial": 8,
    "disable": 6.5,
    "healing": 0
  },
  "bristleback": {
    "midlane": 0,
    "safelane": 7.3,
    "offlane": 7.98,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 8.5,
    "dps": 7.94,
    "push": 4.6,
    "nuke": 3,
    "durable": 9.5,
    "initial": 3,
    "disable": 7.5,
    "healing": 1.5
  },
  "broodmother": {
    "midlane": 11.08,
    "safelane": 8.22,
    "offlane": 10.47,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 9.5,
    "dps": 4.53,
    "push": 5.72,
    "nuke": 4.5,
    "durable": 6,
    "initial": 3,
    "disable": 7,
    "healing": 0
  },
  "centaur-warrunner": {
    "midlane": 0,
    "safelane": 6.05,
    "offlane": 6.82,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 7.3,
    "dps": 6.94,
    "push": 5.73,
    "nuke": 6,
    "durable": 8,
    "initial": 8.5,
    "disable": 8.5,
    "healing": 4.5
  },
  "chaos-knight": {
    "midlane": 6.7,
    "safelane": 5.93,
    "offlane": 6.16,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6,
    "dps": 6.67,
    "push": 5.83,
    "nuke": 8.5,
    "durable": 8,
    "initial": 7.5,
    "disable": 9,
    "healing": 0
  },
  "chen": {
    "midlane": 0,
    "safelane": 8.45,
    "offlane": 9.05,
    "jungle": 9.81,
    "perfer": "Jungle",
    "lane": 7,
    "dps": 2.55,
    "push": 4.62,
    "nuke": 2,
    "durable": 3.5,
    "initial": 3.5,
    "disable": 6,
    "healing": 8.5
  },
  "clinkz": {
    "midlane": 8.63,
    "safelane": 7.95,
    "offlane": 7.51,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 7.5,
    "dps": 6.77,
    "push": 6.55,
    "nuke": 8.5,
    "durable": 4.5,
    "initial": 2,
    "disable": 2,
    "healing": 0
  },
  "crystal-maiden": {
    "midlane": 0,
    "safelane": 6.77,
    "offlane": 6.83,
    "jungle": 6.77,
    "perfer": "Safe Lane",
    "lane": 7,
    "dps": 5.46,
    "push": 2.04,
    "nuke": 2.5,
    "durable": 2,
    "initial": 5,
    "disable": 7.5,
    "healing": 3.5
  },
  "dark-seer": {
    "midlane": 0,
    "safelane": 6.48,
    "offlane": 7.6,
    "jungle": 7.6,
    "perfer": "Off Lane",
    "lane": 7,
    "dps": 6.13,
    "push": 2.59,
    "nuke": 4.5,
    "durable": 7.5,
    "initial": 8.5,
    "disable": 3.5,
    "healing": 5.5
  },
  "dazzle": {
    "midlane": 7.83,
    "safelane": 8.02,
    "offlane": 8.18,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 8,
    "dps": 1.83,
    "push": 2.98,
    "nuke": 1,
    "durable": 4,
    "initial": 3,
    "disable": 5,
    "healing": 8.5
  },
  "death-prophet": {
    "midlane": 7.52,
    "safelane": 6.25,
    "offlane": 6.78,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7.2,
    "dps": 6.96,
    "push": 5.94,
    "nuke": 6.5,
    "durable": 7.5,
    "initial": 3,
    "disable": 5.5,
    "healing": 1.5
  },
  "disruptor": {
    "midlane": 6.58,
    "safelane": 6.43,
    "offlane": 6.48,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6.5,
    "dps": 4.83,
    "push": 2.36,
    "nuke": 4,
    "durable": 2,
    "initial": 7.5,
    "disable": 8,
    "healing": 2.5
  },
  "doom": {
    "midlane": 0,
    "safelane": 6.21,
    "offlane": 8.04,
    "jungle": 6.04,
    "perfer": "Off Lane",
    "lane": 5.5,
    "dps": 5.49,
    "push": 3.56,
    "nuke": 7,
    "durable": 7,
    "initial": 8,
    "disable": 4.5,
    "healing": 1
  },
  "dragon-knight": {
    "midlane": 8.24,
    "safelane": 6.81,
    "offlane": 7.29,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7.5,
    "dps": 6.47,
    "push": 6.1,
    "nuke": 5,
    "durable": 9,
    "initial": 6.5,
    "disable": 7.5,
    "healing": 0
  },
  "drow-ranger": {
    "midlane": 8.19,
    "safelane": 8.09,
    "offlane": 7.16,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 7,
    "dps": 5.78,
    "push": 6.84,
    "nuke": 7,
    "durable": 5,
    "initial": 4,
    "disable": 7,
    "healing": 0
  },
  "earth-spirit": {
    "midlane": 7.93,
    "safelane": 6.84,
    "offlane": 7.47,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 5.5,
    "dps": 4.39,
    "push": 1.38,
    "nuke": 6,
    "durable": 4,
    "initial": 7.5,
    "disable": 7,
    "healing": 2.5
  },
  "earthshaker": {
    "midlane": 4.32,
    "safelane": 4.15,
    "offlane": 4.21,
    "jungle": 3.88,
    "perfer": "Safe Lane",
    "lane": 4,
    "dps": 6.13,
    "push": 2.58,
    "nuke": 7.5,
    "durable": 3,
    "initial": 8.5,
    "disable": 8.5,
    "healing": 1
  },
  "elder-titan": {
    "midlane": 6.07,
    "safelane": 5.93,
    "offlane": 5.89,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 6,
    "dps": 6.01,
    "push": 2.62,
    "nuke": 6.5,
    "durable": 5,
    "initial": 8,
    "disable": 7,
    "healing": 2.5
  },
  "ember-spirit": {
    "midlane": 7.98,
    "safelane": 6.39,
    "offlane": 5.83,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 6,
    "dps": 7.69,
    "push": 4.67,
    "nuke": 6.5,
    "durable": 7.5,
    "initial": 6.5,
    "disable": 8,
    "healing": 1
  },
  "enchantress": {
    "midlane": 7.79,
    "safelane": 6.32,
    "offlane": 9.07,
    "jungle": 6.27,
    "perfer": "Jungle",
    "lane": 6,
    "dps": 5.68,
    "push": 4.04,
    "nuke": 7.5,
    "durable": 6,
    "initial": 3,
    "disable": 4.5,
    "healing": 3.5
  },
  "enigma": {
    "midlane": 0,
    "safelane": 0,
    "offlane": 0,
    "jungle": 6.62,
    "perfer": "Jungle",
    "lane": 6.5,
    "dps": 6.37,
    "push": 4.52,
    "nuke": 4,
    "durable": 4.5,
    "initial": 9,
    "disable": 8,
    "healing": 5.5
  },
  "faceless-void": {
    "midlane": 0,
    "safelane": 8.57,
    "offlane": 10.17,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 8.2,
    "dps": 5.34,
    "push": 5.24,
    "nuke": 7,
    "durable": 8.5,
    "initial": 9,
    "disable": 7,
    "healing": 1
  },
  "natures-prophet": {
    "midlane": 0,
    "safelane": 0,
    "offlane": 9,
    "jungle": 8.08,
    "perfer": "Jungle",
    "lane": 7.7,
    "dps": 6.45,
    "push": 6.71,
    "nuke": 4,
    "durable": 4.5,
    "initial": 3,
    "disable": 9,
    "healing": 3.5
  },
  "gyrocopter": {
    "midlane": 7.61,
    "safelane": 7.53,
    "offlane": 7.47,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6.5,
    "dps": 7.32,
    "push": 4.92,
    "nuke": 4,
    "durable": 7.5,
    "initial": 7.5,
    "disable": 6,
    "healing": 1
  },
  "huskar": {
    "midlane": 9.77,
    "safelane": 9.98,
    "offlane": 9.05,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 8.5,
    "dps": 7.69,
    "push": 5.37,
    "nuke": 7,
    "durable": 9,
    "initial": 3,
    "disable": 7.5,
    "healing": 3.5
  },
  "invoker": {
    "midlane": 9.09,
    "safelane": 0,
    "offlane": 8.34,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 8,
    "dps": 7.65,
    "push": 5.83,
    "nuke": 8.5,
    "durable": 7,
    "initial": 8,
    "disable": 9,
    "healing": 2
  },
  "jakiro": {
    "midlane": 7.38,
    "safelane": 7.21,
    "offlane": 7.45,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 8,
    "dps": 5.57,
    "push": 5.03,
    "nuke": 5.5,
    "durable": 6,
    "initial": 4,
    "disable": 6,
    "healing": 2.5
  },
  "juggernaut": {
    "midlane": 6.28,
    "safelane": 5.86,
    "offlane": 5.4,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 5.5,
    "dps": 7.37,
    "push": 6.32,
    "nuke": 7.5,
    "durable": 7.5,
    "initial": 3,
    "disable": 4,
    "healing": 5.5
  },
  "keeper-of-the-light": {
    "midlane": 8.28,
    "safelane": 8.4,
    "offlane": 8.45,
    "jungle": 8.4,
    "perfer": "Safe Lane",
    "lane": 8.5,
    "dps": 4.73,
    "push": 2.45,
    "nuke": 3,
    "durable": 4,
    "initial": 3,
    "disable": 6,
    "healing": 8
  },
  "kunkka": {
    "midlane": 6.57,
    "safelane": 5.87,
    "offlane": 6.26,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 6,
    "dps": 6.74,
    "push": 3.88,
    "nuke": 5,
    "durable": 7.5,
    "initial": 7.5,
    "disable": 8.5,
    "healing": 2.5
  },
  "legion-commander": {
    "midlane": 5.94,
    "safelane": 5.08,
    "offlane": 5.34,
    "jungle": 5.22,
    "perfer": "Jungle",
    "lane": 5.5,
    "dps": 6.79,
    "push": 6.09,
    "nuke": 7,
    "durable": 7,
    "initial": 9,
    "disable": 4,
    "healing": 2.5
  },
  "leshrac": {
    "midlane": 9.05,
    "safelane": 6.98,
    "offlane": 7.4,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 6.7,
    "dps": 6.48,
    "push": 5.24,
    "nuke": 5.5,
    "durable": 6.5,
    "initial": 5.5,
    "disable": 7.5,
    "healing": 2
  },
  "lich": {
    "midlane": 8.13,
    "safelane": 8.52,
    "offlane": 8.87,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 9,
    "dps": 6.47,
    "push": 2.64,
    "nuke": 3.5,
    "durable": 5.5,
    "initial": 4,
    "disable": 6.5,
    "healing": 3.5
  },
  "lifestealer": {
    "midlane": 0,
    "safelane": 7.55,
    "offlane": 7.07,
    "jungle": 6.56,
    "perfer": "Jungle",
    "lane": 7,
    "dps": 7.15,
    "push": 5.51,
    "nuke": 7.5,
    "durable": 8,
    "initial": 6,
    "disable": 6.5,
    "healing": 2
  },
  "lina": {
    "midlane": 8.21,
    "safelane": 7.92,
    "offlane": 8.06,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7.5,
    "dps": 6.64,
    "push": 4.33,
    "nuke": 8.5,
    "durable": 5,
    "initial": 6.5,
    "disable": 7,
    "healing": 1.5
  },
  "lion": {
    "midlane": 5.99,
    "safelane": 5.98,
    "offlane": 5.89,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6,
    "dps": 3.95,
    "push": 1.84,
    "nuke": 6.5,
    "durable": 2,
    "initial": 9,
    "disable": 9,
    "healing": 1.5
  },
  "lone-druid": {
    "midlane": 11.92,
    "safelane": 10.27,
    "offlane": 11.21,
    "jungle": 11.21,
    "perfer": "Off Lane",
    "lane": 7.8,
    "dps": 4.96,
    "push": 6.25,
    "nuke": 4,
    "durable": 9,
    "initial": 3,
    "disable": 7.5,
    "healing": 0
  },
  "luna": {
    "midlane": 6.28,
    "safelane": 5.9,
    "offlane": 5.43,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6,
    "dps": 7.68,
    "push": 7.06,
    "nuke": 7.5,
    "durable": 7,
    "initial": 2,
    "disable": 4,
    "healing": 0
  },
  "lycan": {
    "midlane": 0,
    "safelane": 7.5,
    "offlane": 6.75,
    "jungle": 7.38,
    "perfer": "Jungle",
    "lane": 6.5,
    "dps": 5.15,
    "push": 6.59,
    "nuke": 7.5,
    "durable": 9,
    "initial": 3,
    "disable": 3,
    "healing": 1
  },
  "magnus": {
    "midlane": 5.18,
    "safelane": 4.2,
    "offlane": 5.11,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 5,
    "dps": 5.4,
    "push": 3.68,
    "nuke": 3.5,
    "durable": 5,
    "initial": 8.5,
    "disable": 5,
    "healing": 0
  },
  "medusa": {
    "midlane": 9.24,
    "safelane": 8.49,
    "offlane": 8.45,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 8.5,
    "dps": 7.57,
    "push": 6.19,
    "nuke": 3,
    "durable": 10,
    "initial": 3,
    "disable": 7.5,
    "healing": 0.5
  },
  "meepo": {
    "midlane": 8.56,
    "safelane": 6.53,
    "offlane": 5.28,
    "jungle": 5.78,
    "perfer": "Mid Lane",
    "lane": 7.5,
    "dps": 7.27,
    "push": 6.88,
    "nuke": 9,
    "durable": 7,
    "initial": 9,
    "disable": 9,
    "healing": 0
  },
  "mirana": {
    "midlane": 4.9,
    "safelane": 4.32,
    "offlane": 4.64,
    "jungle": 4.38,
    "perfer": "Off Lane",
    "lane": 4.5,
    "dps": 6.71,
    "push": 4.67,
    "nuke": 8,
    "durable": 5,
    "initial": 6,
    "disable": 4.5,
    "healing": 0
  },
  "morphling": {
    "midlane": 6.1,
    "safelane": 5.82,
    "offlane": 5.21,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 5.5,
    "dps": 7.58,
    "push": 6.59,
    "nuke": 9,
    "durable": 9.5,
    "initial": 7.5,
    "disable": 7.5,
    "healing": 0
  },
  "naga-siren": {
    "midlane": 8.38,
    "safelane": 6.66,
    "offlane": 6.45,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6.7,
    "dps": 5.8,
    "push": 5.48,
    "nuke": 5,
    "durable": 8.5,
    "initial": 8.5,
    "disable": 6,
    "healing": 1.5
  },
  "necrophos": {
    "midlane": 7.3,
    "safelane": 7.54,
    "offlane": 8.15,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 7.5,
    "dps": 7.3,
    "push": 3.68,
    "nuke": 7.5,
    "durable": 8.5,
    "initial": 2,
    "disable": 2,
    "healing": 8
  },
  "shadow-fiend": {
    "midlane": 8.08,
    "safelane": 6.76,
    "offlane": 0,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7.5,
    "dps": 7.91,
    "push": 6.15,
    "nuke": 7.5,
    "durable": 7,
    "initial": 2,
    "disable": 2,
    "healing": 0
  },
  "night-stalker": {
    "midlane": 5.73,
    "safelane": 5.05,
    "offlane": 5.75,
    "jungle": 5.28,
    "perfer": "Off Lane",
    "lane": 5.5,
    "dps": 5.82,
    "push": 5.02,
    "nuke": 4,
    "durable": 7.5,
    "initial": 4,
    "disable": 8,
    "healing": 0
  },
  "nyx-assassin": {
    "midlane": 4.99,
    "safelane": 4.73,
    "offlane": 5.16,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 5,
    "dps": 6.79,
    "push": 1.65,
    "nuke": 5,
    "durable": 6,
    "initial": 6.5,
    "disable": 7.5,
    "healing": 1.5
  },
  "outworld-devourer": {
    "midlane": 9.13,
    "safelane": 8.77,
    "offlane": 7.74,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 8.5,
    "dps": 8.01,
    "push": 5.02,
    "nuke": 7.5,
    "durable": 7.5,
    "initial": 3,
    "disable": 4.5,
    "healing": 4.5
  },
  "ogre-magi": {
    "midlane": 5.75,
    "safelane": 5.46,
    "offlane": 5.71,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6,
    "dps": 5.33,
    "push": 2.43,
    "nuke": 4.5,
    "durable": 5,
    "initial": 6.5,
    "disable": 6.5,
    "healing": 1.5
  },
  "omniknight": {
    "midlane": 0,
    "safelane": 5.91,
    "offlane": 6.26,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6,
    "dps": 3.3,
    "push": 2.97,
    "nuke": 3,
    "durable": 8,
    "initial": 2,
    "disable": 2,
    "healing": 9
  },
  "oracle": {
    "midlane": 8.84,
    "safelane": 9.03,
    "offlane": 8.7,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 7.7,
    "dps": 3.31,
    "push": 2.42,
    "nuke": 3.5,
    "durable": 5.5,
    "initial": 2,
    "disable": 4,
    "healing": 9.5
  },
  "phantom-assassin": {
    "midlane": 6.76,
    "safelane": 5.92,
    "offlane": 5.59,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6.5,
    "dps": 7.91,
    "push": 5.31,
    "nuke": 9,
    "durable": 8.5,
    "initial": 8,
    "disable": 8.5,
    "healing": 0
  },
  "phantom-lancer": {
    "midlane": 5.62,
    "safelane": 5.27,
    "offlane": 5.22,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 5,
    "dps": 6.21,
    "push": 5.25,
    "nuke": 7,
    "durable": 8.5,
    "initial": 4.5,
    "disable": 7.5,
    "healing": 0
  },
  "phoenix": {
    "midlane": 6.57,
    "safelane": 6.49,
    "offlane": 6.55,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 6.5,
    "dps": 6.62,
    "push": 2.56,
    "nuke": 4,
    "durable": 7.5,
    "initial": 7,
    "disable": 6,
    "healing": 4.5
  },
  "puck": {
    "midlane": 8,
    "safelane": 0,
    "offlane": 7.59,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7.5,
    "dps": 7.38,
    "push": 3.66,
    "nuke": 6.5,
    "durable": 7.5,
    "initial": 8,
    "disable": 5.5,
    "healing": 1
  },
  "pudge": {
    "midlane": 5.85,
    "safelane": 5.48,
    "offlane": 6.06,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 6,
    "dps": 6.97,
    "push": 2.29,
    "nuke": 5.5,
    "durable": 8,
    "initial": 8,
    "disable": 8,
    "healing": 2.5
  },
  "pugna": {
    "midlane": 8.84,
    "safelane": 8.81,
    "offlane": 8.99,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 8,
    "dps": 6.95,
    "push": 5.71,
    "nuke": 6.5,
    "durable": 3,
    "initial": 2,
    "disable": 5,
    "healing": 3.5
  },
  "queen-of-pain": {
    "midlane": 8.54,
    "safelane": 7.94,
    "offlane": 8.33,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7.5,
    "dps": 7.29,
    "push": 4.37,
    "nuke": 8.5,
    "durable": 8.5,
    "initial": 3,
    "disable": 6.5,
    "healing": 1
  },
  "clockwerk": {
    "midlane": 0,
    "safelane": 5.51,
    "offlane": 6.39,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 6.5,
    "dps": 7.77,
    "push": 2.69,
    "nuke": 3,
    "durable": 7.5,
    "initial": 8.5,
    "disable": 6,
    "healing": 1
  },
  "razor": {
    "midlane": 8.97,
    "safelane": 7.86,
    "offlane": 8.9,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 8.5,
    "dps": 7.29,
    "push": 5.44,
    "nuke": 4.5,
    "durable": 8,
    "initial": 3,
    "disable": 3,
    "healing": 0
  },
  "riki": {
    "midlane": 6.48,
    "safelane": 6,
    "offlane": 6.57,
    "jungle": 8,
    "perfer": "Off Lane",
    "lane": 6.5,
    "dps": 7.44,
    "push": 3.33,
    "nuke": 6,
    "durable": 7.5,
    "initial": 5,
    "disable": 7,
    "healing": 0
  },
  "rubick": {
    "midlane": 3.5,
    "safelane": 3.59,
    "offlane": 3.52,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 3.5,
    "dps": 4.15,
    "push": 1.91,
    "nuke": 5,
    "durable": 3,
    "initial": 7,
    "disable": 7,
    "healing": 2.5
  },
  "sand-king": {
    "midlane": 7.86,
    "safelane": 7.27,
    "offlane": 7.7,
    "jungle": 7.7,
    "perfer": "Off Lane",
    "lane": 7.5,
    "dps": 6.5,
    "push": 2.29,
    "nuke": 6.5,
    "durable": 6.5,
    "initial": 8.5,
    "disable": 8.5,
    "healing": 1
  },
  "shadow-demon": {
    "midlane": 8.57,
    "safelane": 8.14,
    "offlane": 7.99,
    "jungle": 8.14,
    "perfer": "Safe Lane",
    "lane": 7.7,
    "dps": 4.6,
    "push": 3.72,
    "nuke": 3,
    "durable": 3,
    "initial": 6,
    "disable": 6.5,
    "healing": 5
  },
  "shadow-shaman": {
    "midlane": 6.11,
    "safelane": 6.02,
    "offlane": 5.98,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6.3,
    "dps": 5.2,
    "push": 6.18,
    "nuke": 3.5,
    "durable": 2,
    "initial": 7,
    "disable": 7.5,
    "healing": 2.5
  },
  "timbersaw": {
    "midlane": 8.04,
    "safelane": 6.61,
    "offlane": 7.52,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 7.5,
    "dps": 8.09,
    "push": 2.76,
    "nuke": 4,
    "durable": 9,
    "initial": 4,
    "disable": 7.5,
    "healing": 1.5
  },
  "silencer": {
    "midlane": 7.98,
    "safelane": 8.22,
    "offlane": 8.44,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 8.5,
    "dps": 6.38,
    "push": 4.41,
    "nuke": 2.5,
    "durable": 4,
    "initial": 5.5,
    "disable": 3.5,
    "healing": 2
  },
  "wraith-king": {
    "midlane": 0,
    "safelane": 4.89,
    "offlane": 4.72,
    "jungle": 4.43,
    "perfer": "Safe Lane",
    "lane": 5,
    "dps": 6.71,
    "push": 5.78,
    "nuke": 7.5,
    "durable": 9.5,
    "initial": 7.5,
    "disable": 7,
    "healing": 3
  },
  "skywrath-mage": {
    "midlane": 7.47,
    "safelane": 7.1,
    "offlane": 7.13,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 7,
    "dps": 6.62,
    "push": 2.39,
    "nuke": 6.5,
    "durable": 3,
    "initial": 5,
    "disable": 5,
    "healing": 2.5
  },
  "slardar": {
    "midlane": 0,
    "safelane": 6.02,
    "offlane": 6.87,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 6.5,
    "dps": 4.47,
    "push": 3.57,
    "nuke": 6,
    "durable": 7.5,
    "initial": 8,
    "disable": 9.5,
    "healing": 1
  },
  "slark": {
    "midlane": 5.09,
    "safelane": 4.86,
    "offlane": 4.44,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 5,
    "dps": 7.3,
    "push": 5.67,
    "nuke": 6,
    "durable": 8.5,
    "initial": 3,
    "disable": 8,
    "healing": 0
  },
  "sniper": {
    "midlane": 6.99,
    "safelane": 6.02,
    "offlane": 6.26,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7,
    "dps": 8.2,
    "push": 5.73,
    "nuke": 5.5,
    "durable": 7,
    "initial": 2,
    "disable": 4,
    "healing": 0
  },
  "spectre": {
    "midlane": 0,
    "safelane": 4.18,
    "offlane": 3.7,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 4,
    "dps": 9.03,
    "push": 5,
    "nuke": 4,
    "durable": 7.5,
    "initial": 2,
    "disable": 6,
    "healing": 0
  },
  "spirit-breaker": {
    "midlane": 7.05,
    "safelane": 6.33,
    "offlane": 7.06,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 6.5,
    "dps": 6.21,
    "push": 3.53,
    "nuke": 6,
    "durable": 7.5,
    "initial": 7.5,
    "disable": 8,
    "healing": 1
  },
  "storm-spirit": {
    "midlane": 7.11,
    "safelane": 6.23,
    "offlane": 0,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7,
    "dps": 7.55,
    "push": 4.61,
    "nuke": 8,
    "durable": 8,
    "initial": 8,
    "disable": 9,
    "healing": 1.5
  },
  "sven": {
    "midlane": 0,
    "safelane": 6.37,
    "offlane": 5.91,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6.5,
    "dps": 7.8,
    "push": 6.19,
    "nuke": 9.5,
    "durable": 8.5,
    "initial": 6.5,
    "disable": 5,
    "healing": 0
  },
  "techies": {
    "midlane": 9.18,
    "safelane": 8.55,
    "offlane": 9.88,
    "jungle": 8.38,
    "perfer": "Off Lane",
    "lane": 8.5,
    "dps": 6.65,
    "push": 1.07,
    "nuke": 6.5,
    "durable": 3,
    "initial": 6.5,
    "disable": 2,
    "healing": 1.5
  },
  "templar-assassin": {
    "midlane": 8.8,
    "safelane": 6.53,
    "offlane": 6.15,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7.5,
    "dps": 7.03,
    "push": 5.96,
    "nuke": 9,
    "durable": 7,
    "initial": 4.5,
    "disable": 8,
    "healing": 0
  },
  "terrorblade": {
    "midlane": 6.82,
    "safelane": 6.38,
    "offlane": 5.83,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6,
    "dps": 6.58,
    "push": 7.1,
    "nuke": 8.5,
    "durable": 7.5,
    "initial": 2,
    "disable": 4.5,
    "healing": 1
  },
  "tidehunter": {
    "midlane": 0,
    "safelane": 8.33,
    "offlane": 9.45,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 8.5,
    "dps": 5.37,
    "push": 2.76,
    "nuke": 4,
    "durable": 9,
    "initial": 9,
    "disable": 5.5,
    "healing": 2.5
  },
  "tinker": {
    "midlane": 8.85,
    "safelane": 0,
    "offlane": 0,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 8.5,
    "dps": 9.79,
    "push": 0.82,
    "nuke": 8.5,
    "durable": 8.5,
    "initial": 3,
    "disable": 6.5,
    "healing": 1
  },
  "tiny": {
    "midlane": 7.41,
    "safelane": 5.62,
    "offlane": 5.8,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 6,
    "dps": 7.18,
    "push": 5.62,
    "nuke": 9,
    "durable": 8,
    "initial": 8,
    "disable": 7,
    "healing": 1
  },
  "treant-protector": {
    "midlane": 0,
    "safelane": 7.71,
    "offlane": 7.83,
    "jungle": 7.08,
    "perfer": "Safe Lane",
    "lane": 8,
    "dps": 2.23,
    "push": 2.83,
    "nuke": 1,
    "durable": 5.5,
    "initial": 6.5,
    "disable": 4.5,
    "healing": 4.5
  },
  "troll-warlord": {
    "midlane": 7.14,
    "safelane": 7.14,
    "offlane": 6.75,
    "jungle": 6.41,
    "perfer": "Safe Lane",
    "lane": 7.5,
    "dps": 6.7,
    "push": 6.59,
    "nuke": 7,
    "durable": 8,
    "initial": 2,
    "disable": 6.5,
    "healing": 0
  },
  "tusk": {
    "midlane": 5.71,
    "safelane": 4.91,
    "offlane": 5.5,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 4.2,
    "dps": 6.01,
    "push": 3.16,
    "nuke": 6,
    "durable": 6.5,
    "initial": 7.5,
    "disable": 7.5,
    "healing": 2.5
  },
  "undying": {
    "midlane": 0,
    "safelane": 8.52,
    "offlane": 9.45,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 8.2,
    "dps": 4.54,
    "push": 2.98,
    "nuke": 3,
    "durable": 8,
    "initial": 7.5,
    "disable": 5.5,
    "healing": 6.5
  },
  "underlord": {
    "midlane": 7.13,
    "safelane": 7.03,
    "offlane": 9,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 8.5,
    "dps": 6.87,
    "push": 5.08,
    "nuke": 4,
    "durable": 8,
    "initial": 7.5,
    "disable": 5.5,
    "healing": 4.5
  },
  "ursa": {
    "midlane": 7.17,
    "safelane": 6.5,
    "offlane": 6.76,
    "jungle": 6.5,
    "perfer": "Safe Lane",
    "lane": 6.5,
    "dps": 7.54,
    "push": 4.93,
    "nuke": 10,
    "durable": 8.5,
    "initial": 8.5,
    "disable": 8,
    "healing": 0
  },
  "vengeful-spirit": {
    "midlane": 5.18,
    "safelane": 4.97,
    "offlane": 5.07,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 5,
    "dps": 4.15,
    "push": 4.18,
    "nuke": 4,
    "durable": 4,
    "initial": 7.5,
    "disable": 5.5,
    "healing": 5
  },
  "venomancer": {
    "midlane": 9.2,
    "safelane": 8.87,
    "offlane": 9.22,
    "jungle": 8.87,
    "perfer": "Safe Lane",
    "lane": 8.8,
    "dps": 7.89,
    "push": 4.35,
    "nuke": 4.5,
    "durable": 7,
    "initial": 6.5,
    "disable": 7.5,
    "healing": 2
  },
  "viper": {
    "midlane": 9.22,
    "safelane": 7.92,
    "offlane": 8.93,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 8.5,
    "dps": 7.23,
    "push": 5.61,
    "nuke": 4,
    "durable": 8.5,
    "initial": 7.5,
    "disable": 7.5,
    "healing": 2.5
  },
  "visage": {
    "midlane": 8.17,
    "safelane": 7.28,
    "offlane": 7.19,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 5.7,
    "dps": 5.47,
    "push": 4.64,
    "nuke": 4,
    "durable": 6,
    "initial": 6.5,
    "disable": 7,
    "healing": 2
  },
  "warlock": {
    "midlane": 6.96,
    "safelane": 7.07,
    "offlane": 7.26,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 7.3,
    "dps": 6.85,
    "push": 5.2,
    "nuke": 3,
    "durable": 6,
    "initial": 9,
    "disable": 6,
    "healing": 4.5
  },
  "weaver": {
    "midlane": 8.28,
    "safelane": 7.74,
    "offlane": 8.33,
    "jungle": 0,
    "perfer": "Off Lane",
    "lane": 8,
    "dps": 7.39,
    "push": 6.04,
    "nuke": 5.5,
    "durable": 8.5,
    "initial": 3,
    "disable": 5.5,
    "healing": 0
  },
  "windranger": {
    "midlane": 7.75,
    "safelane": 6.9,
    "offlane": 7.28,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 7,
    "dps": 6.36,
    "push": 5.69,
    "nuke": 7,
    "durable": 5,
    "initial": 7.5,
    "disable": 7.5,
    "healing": 1
  },
  "winter-wyvern": {
    "midlane": 8.17,
    "safelane": 7.98,
    "offlane": 7.69,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 7,
    "dps": 3.48,
    "push": 2.28,
    "nuke": 2,
    "durable": 4,
    "initial": 7,
    "disable": 3.5,
    "healing": 6.5
  },
  "io": {
    "midlane": 7.19,
    "safelane": 5.68,
    "offlane": 6.24,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 4,
    "dps": 6.79,
    "push": 6.09,
    "nuke": 3.5,
    "durable": 7,
    "initial": 2,
    "disable": 7.5,
    "healing": 9
  },
  "witch-doctor": {
    "midlane": 8.84,
    "safelane": 9.05,
    "offlane": 9.13,
    "jungle": 0,
    "perfer": "Safe Lane",
    "lane": 8.5,
    "dps": 5.24,
    "push": 2.79,
    "nuke": 7,
    "durable": 3.5,
    "initial": 6.5,
    "disable": 6.5,
    "healing": 5
  },
  "zeus": {
    "midlane": 8.92,
    "safelane": 7.72,
    "offlane": 8.11,
    "jungle": 0,
    "perfer": "Mid Lane",
    "lane": 8,
    "dps": 10,
    "push": 2.27,
    "nuke": 8,
    "durable": 5,
    "initial": 3,
    "disable": 6.5,
    "healing": 1.5
  }
};